package-lock.json
src/app/app.module.ts
src/app/app.routing.ts
src/app/common/header/header.component.html
src/app/common/header/header.component.scss
src/app/views/updatepasswrod/confirmed.validator.ts
src/app/views/updatepasswrod/updatepasswrod.component.html
src/app/views/updatepasswrod/updatepasswrod.component.scss
src/app/views/updatepasswrod/updatepasswrod.component.spec.ts
src/app/views/updatepasswrod/updatepasswrod.component.ts
src/index.html

today work

---

src/app/views/dish/dining-table/dining-table.component.html
src/app/views/dish/dish-category-config/dish-category-config.component.html
src/app/views/dish/dish-menu-new/dish-menu-new.component.html
src/app/views/dish/kot-items/kot-items.component.html
src/app/views/dish/kot-items/kot-items.component.ts
src/app/views/hotel-admin/hotel-admin.component.html

bill config

---

src/app/common/header/header.component.html
src/app/views/dish/dining-table/dining-table.component.html
src/app/views/dish/dining-table/dining-table.component.scss
src/app/views/dish/dish-menu-new/dish-menu-new.component.html
src/app/views/dish/dish-menu-new/dish-menu-new.component.scss
src/app/views/dish/dish-menu-new/dish-menu-new.component.ts
src/app/views/dish/dish.component.scss
src/app/views/user/user-config/user-config.component.ts

New Design

---

src/app/app.component.html
src/app/common/header/header.component.html
src/app/common/header/header.component.ts
src/app/common/sidebar/sidebar.component.html
src/app/common/sidebar/sidebar.component.ts
src/app/views/dish/dish-category-config/dish-category-config.component.html
src/app/views/dish/dish-menu-new/dish-menu-new.component.html
src/app/views/dish/dish.component.html
src/app/views/dish/kot-items/kot-items.component.html
src/app/views/dish/kot-items/kot-items.component.scss
src/app/views/dish/kot-items/kot-items.component.ts
src/app/views/dish/orders-list/orders-list.component.html
src/app/views/hotel-admin/hotel-admin.component.html
src/app/views/hotel-admin/hotel-setting/hotel-setting.component.html
src/app/views/hotel-admin/hotel-setting/hotel-setting.component.ts
src/app/views/hotel-admin/table-configuration/table-configuration.component.html
src/app/views/user/user-config/user-config.component.html
src/app/views/user/user-feedback/user-feedback.component.html
src/app/views/user/user-feedback/user-feedback.component.ts

dish button works today change

---

package.json
src/app/app.module.ts
src/app/models/dish.ts
src/app/models/historydata.ts
src/app/service/enum.service.ts
src/app/views/datahistory/datahistory.component.html
src/app/views/datahistory/datahistory.component.spec.ts
src/app/views/datahistory/datahistory.component.ts
src/app/views/dish/dish-menu-new/dish-menu-new.component.ts
src/app/views/dish/dish-menu/dish-menu.component.html
src/app/views/dish/dish.component.html
src/app/views/forgotpassword/forgotpassword.component.scss
src/app/views/forgotpassword/forgotpassword.component.ts
src/app/views/hotel-admin/hotel-admin-routing.module.ts
src/app/views/hotel-admin/hotel-admin.module.ts
src/app/views/hotel-admin/hotel-setting/hotel-setting.component.html
src/app/views/hotel-admin/hotel-setting/hotel-setting.component.ts
src/app/views/report/backdata/backdata.component.html
src/app/views/report/backdata/backdata.component.spec.ts
src/app/views/report/backdata/backdata.component.ts
src/app/views/report/historydata/historydata.component.html
src/app/views/report/historydata/historydata.component.ts
src/app/views/report/report.component.html
src/app/views/report/report.module.ts
src/app/views/report/today-summary/today-summary.component.html
src/app/views/updatepasswrod/updatepasswrod.component.html

Report Changes

---

src/app/app.module.ts
src/app/constant/api.ts
src/app/models/setting.ts
src/app/service/user.service.ts
src/app/shared/order-status/order-status.component.html
src/app/shared/order-status/order-status.component.scss
src/app/shared/order-status/order-status.component.ts
src/app/views/invoice/invoice.component.html
src/app/views/invoice/invoice.component.ts
src/app/views/report/backdata/backdata.component.html
src/app/views/report/bar-chart/bar-chart.component.html
src/app/views/report/fooditem/fooditem.component.html
src/app/views/report/fooditem/fooditem.component.spec.ts
src/app/views/report/fooditem/fooditem.component.ts
src/app/views/report/report.component.html
src/app/views/report/top-cust-data/top-cust-data.component.html
src/app/views/report/top-cust-data/top-cust-data.component.ts
src/app/views/report/week-summary/week-summary.component.html
src/app/views/setting/setting.component.html
src/app/views/setting/setting.component.ts
src/app/views/updatepasswrod/updatepasswrod.component.html

User Setting

---

src/app/common/sidebar/sidebar.component.html
src/app/common/sidebar/sidebar.component.scss
src/app/common/sidebar/sidebar.component.ts
src/app/service/user.service.ts
src/app/shared/order-status/order-status.component.html
src/app/views/dish/kot-items/kot-items.component.html
src/app/views/dish/kot-items/kot-items.component.scss
src/app/views/setting/setting.component.html
src/index.html

bill print issue

---

src/app/app.component.ts
src/app/common/header/header.component.html
src/app/service/common.service.ts
src/app/views/datahistory/datahistory.component.html
src/app/views/datahistory/datahistory.component.ts
src/app/views/dish/dining-table/dining-table.component.html
src/app/views/dish/dining-table/dining-table.component.scss
src/app/views/dish/dish-category-config/dish-category-config.component.html
src/app/views/dish/dish-category-config/dish-category-config.component.scss
src/app/views/dish/dish-menu-new/dish-menu-new.component.html
src/app/views/dish/dish-menu-new/dish-menu-new.component.scss
src/app/views/dish/dish-menu-new/dish-menu-new.component.ts
src/app/views/dish/dish.component.html
src/app/views/dish/kot-items/kot-items.component.html
src/app/views/dish/orders-list/orders-list.component.scss
src/app/views/hotel-admin/hotel-admin-routing.module.ts
src/app/views/hotel-admin/hotel-admin.component.html
src/app/views/hotel-admin/hotel-setting/hotel-setting.component.html
src/app/views/hotel-admin/hotel-setting/hotel-setting.component.scss
src/app/views/hotel-admin/table-configuration/table-configuration.compoent.scss
src/app/views/hotel-admin/table-configuration/table-configuration.component.html
src/app/views/report/fooditem/fooditem.component.html
src/app/views/setting/setting.component.ts
src/app/views/user/user-config/user-config.component.scss
src/app/views/user/user-form/user-form.component.html
src/app/views/user/user-form/user-form.component.ts

excel propertise changes

---

src/app/common/sidebar/sidebar.component.ts
src/app/views/help/help.component.scss
src/app/views/report/backdata/backdata.component.html
src/app/views/report/backdata/backdata.component.scss
src/app/views/report/historydata/historydata.component.html
src/app/views/report/historydata/historydata.component.scss
src/app/views/report/today-summary/today-summary.component.scss

report css

---

src/app/views/dish/dish-category-config/dish-category-config.component.html
src/app/views/dish/dish.component.html
src/app/views/dish/dish.component.scss
src/app/views/hotel-admin/table-configuration/table-configuration.component.html

search bar

---

src/app/common/header/header.component.ts
src/app/service/common.service.ts
src/app/views/admin-setting/admin-setting.component.html
src/app/views/admin-setting/admin-setting.component.scss
src/app/views/dish/dish-menu-new/dish-menu-new.component.ts
src/app/views/dish/kot-items/kot-items.component.html
src/app/views/dish/kot-items/kot-items.component.ts
src/app/views/report/today-summary/today-summary.component.html
src/app/views/report/today-summary/today-summary.component.scss
src/app/views/setting/setting.component.ts

latest setting

---

src/app/models/report.ts
src/app/service/cart.service.ts
src/app/views/dish/billing/billing.component.ts
src/app/views/dish/dish-category-config/dish-category-config.component.ts
src/app/views/dish/dish-menu-new/dish-menu-new.component.ts
src/app/views/dish/orders-list/orders-list.component.html
src/app/views/dish/orders-list/orders-list.component.ts
src/app/views/report/bar-chart/bar-chart.component.html
src/app/views/report/bar-chart/bar-chart.component.ts
src/app/views/report/historydata/historydata.component.html
src/app/views/report/report.component.html
src/app/views/report/report.component.ts
src/app/views/report/today-summary/today-summary.component.html
src/app/views/report/today-summary/today-summary.component.ts
src/app/views/report/week-summary/week-summary.component.html
src/app/views/report/week-summary/week-summary.component.ts

Dish Issue Solved

---

src/app/constant/api.ts
src/app/models/historydata.ts
src/app/views/report/backdata/backdata.component.html
src/app/views/report/backdata/backdata.component.ts
src/app/views/report/bar-chart/bar-chart.component.html
src/app/views/report/bar-chart/bar-chart.component.ts
src/app/views/report/historydata/historydata.component.html
src/app/views/report/historydata/historydata.component.ts
src/app/views/report/report.component.html
src/app/views/report/report.component.ts
src/app/views/report/today-summary/today-summary.component.html
src/app/views/report/top-cust-data/top-cust-data.component.html
src/app/views/report/top-cust-data/top-cust-data.component.ts
src/app/views/report/week-summary/week-summary.component.html
src/app/views/report/week-summary/week-summary.component.ts

Today Summary Report

---

src/app/views/report/top-cust-data/top-cust-data.component.ts

repeated customer done

---

src/app/models/setting.ts
src/app/service/auth.service.ts
src/app/service/share-data.service.ts
src/app/service/user.service.ts
src/app/views/dish/dish-menu-new/dish-menu-new.component.html
src/app/views/dish/dish-menu-new/dish-menu-new.component.ts
src/app/views/login/userLogin.component.ts
src/app/views/setting/setting.component.html
src/app/views/setting/setting.component.ts

Setting Language Problem and dish image 

---

src/app/models/shopping-cart.ts
src/app/service/user.service.ts
src/app/shared/order-status/order-status.component.html
src/app/shared/order-status/order-status.component.ts
src/app/views/datahistory/datahistory.component.html
src/app/views/datahistory/datahistory.component.ts
src/app/views/dish/dish-menu-new/dish-menu-new.component.html
src/app/views/dish/dish-menu-new/dish-menu-new.component.ts
src/app/views/dish/kot-items/kot-items.component.html
src/app/views/dish/kot-items/kot-items.component.ts
src/app/views/dish/orders-list/orders-list.component.html
src/app/views/report/backdata/backdata.component.html
src/app/views/report/backdata/backdata.component.ts
src/app/views/report/top-cust-data/top-cust-data.component.html
src/app/views/report/topdata/topdata.component.html

user issues

---

src/app/common/sidebar/sidebar.component.ts
src/app/views/dish/dish-menu-new/dish-menu-new.component.html
src/app/views/dish/dish-menu-new/dish-menu-new.component.scss
src/app/views/dish/dish-menu-new/dish-menu-new.component.spec.ts
src/app/views/dish/dish-menu-new/dish-menu-new.component.ts

Signed-off-by: yunus <yunus.farooqui@gmail.com>

dish dialog ad

---

src/app/app.component.ts
src/app/app.routing.ts
src/app/service/cart.service.ts
src/app/shared/order-status/order-status.component.html
src/app/shared/order-status/order-status.component.ts
src/app/views/datahistory/datahistory.component.html
src/app/views/datahistory/datahistory.component.ts
src/app/views/dish/billing/billing.component.ts
src/app/views/dish/dining-table/dining-table.component.ts
src/app/views/dish/dish-menu-new/dish-menu-new.component.html
src/app/views/dish/dish-menu-new/dish-menu-new.component.ts
src/app/views/forgotpassword/forgotpassword.component.html
src/app/views/forgotpassword/forgotpassword.component.ts
src/app/views/invoice/invoice.component.html
src/app/views/invoice/invoice.component.ts
src/app/views/register/register.component.css
src/app/views/register/register.component.html
src/app/views/register/register.component.ts
src/app/views/resetpasword/resetpasword.component.ts

all function

---

src/app/shared/order-status/order-status.component.html
src/app/shared/order-status/order-status.component.scss
src/app/views/dish/dish.component.ts
src/app/views/dish/orders-list/orders-list.component.ts
src/app/views/hotel-admin/table-configuration/table-configuration.component.html
src/app/views/hotel-admin/table-configuration/table-configuration.component.ts
src/app/views/invoice/invoice.component.html
src/app/views/invoice/invoice.component.scss
src/app/views/login/userLogin.component.ts

orderstatus

---

src/app/app.component.ts
src/app/constant/api.ts
src/app/models/franchise.ts
src/app/service/capnfran.service.ts
src/app/views/captain/captain.component.html
src/app/views/captain/captain.component.ts
src/app/views/franchise/franchise.component.html
src/app/views/franchise/franchise.component.ts

captain post done

---

src/app/common/header/header.component.html
src/app/common/header/header.component.ts
src/app/models/setting.ts
src/app/views/dish/dining-table/dining-table.component.ts
src/app/views/dish/dish-menu-new/dish-menu-new.component.html
src/app/views/dish/dish-menu-new/dish-menu-new.component.scss
src/app/views/dish/dish-menu-new/dish-menu-new.component.ts
src/app/views/inventory/purchase/purchase.component.html
src/app/views/inventory/purchase/purchase.component.ts
src/app/views/inventory/recipes/recipes.component.html
src/app/views/inventory/recipes/recipes.component.ts
src/app/views/inventory/stockstatus/stockstatus.component.html
src/app/views/inventory/stockstatus/stockstatus.component.ts
src/app/views/setting/setting.component.html
src/app/views/setting/setting.component.ts

tablet view 

---

src/app/views/dish/dish-menu-new/dish-menu-new.component.ts
src/app/views/report/backdata/backdata.component.ts
src/app/views/report/historydata/historydata.component.html
src/app/views/report/historydata/historydata.component.ts
src/app/views/report/report.component.html
src/app/views/report/report.component.ts
src/app/views/report/today-summary/today-summary.component.ts
src/app/views/report/top-cust-data/top-cust-data.component.html
src/app/views/report/top-cust-data/top-cust-data.component.ts
src/app/views/report/topdata/topdata.component.ts

bill category

---

src/app/models/franchise.ts
src/app/service/capnfran.service.ts
src/app/views/captain/captain.component.ts
src/app/views/franchise/franchise.component.html
src/app/views/franchise/franchise.component.ts
src/app/views/report/historydata/historydata.component.ts
src/app/views/report/report.component.html
src/app/views/report/report.component.ts
src/app/views/report/top-cust-data/top-cust-data.component.ts
src/app/views/report/topdata/topdata.component.ts

report data
